version: "3.9"

services:
  airflow:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    container_name: code-pipeline-airflow
    restart: unless-stopped
    env_file:
      - .env
      - airflow/config/airflow.env
    environment:
      PYTHONPATH: /opt/airflow
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/config:/opt/airflow/config
      - ./worker:/opt/airflow/worker
      - ./infra:/opt/airflow/infra
      - ./airflow/logs:/opt/airflow/logs
      - ./local_data:/opt/airflow/local_data
      - ./benchmark_data:/opt/airflow/benchmark_data
    command: >
      bash -c "
      echo 'Waiting for Tor-Proxy (9050)...' &&
      until (echo > /dev/tcp/tor-proxy/9050) >/dev/null 2>&1; do
        echo 'Tor is not ready yet... sleeping'
        sleep 3
      done &&
      echo 'Tor-Proxy is UP! Starting Airflow...' &&
      airflow db migrate &&
      (
        airflow users create --username admin --firstname admin --lastname admin --role Admin --email admin@example.com --password admin ||
        airflow users reset-password --username admin --password admin
      ) &&
      airflow scheduler & exec airflow webserver
      "
    depends_on:
      - tor-proxy
  tor-proxy:
    image: dockurr/tor
    container_name: tor-proxy
    environment:
      - TOR_CONTROL_PORT=9051
    ports:
      - "9050:9050"
      - "9051:9051"
    restart: always
