import hashlib
import keyword
import re
import builtins
from dataclasses import dataclass
from typing import Any

from worker.common.config import settings

try:
    from tree_sitter import Node, Tree
except ImportError:  # pragma: no cover - optional dependency fallback
    Node = Any
    Tree = Any


CODE_CHUNK_INDEX_TEMPLATE_NAME = "code_chunk_index"
CODE_CHUNK_INDEX_ALIAS = settings.code_chunk_index_alias

FUNCTION_NODE_TYPES_BY_LANGUAGE = {
    "python": {"function_definition", "decorated_definition"},
    "javascript": {
        "function_declaration",
        "generator_function_declaration",
        "method_definition",
        "arrow_function",
    },
    "typescript": {
        "function_declaration",
        "generator_function_declaration",
        "method_definition",
        "arrow_function",
    },
    "java": {"method_declaration", "constructor_declaration"},
    "go": {"function_declaration", "method_declaration"},
    "rust": {"function_item"},
    "c": {"function_definition"},
    "cpp": {"function_definition"},
    "csharp": {"method_declaration", "constructor_declaration", "local_function_statement"},
    "php": {"function_definition", "method_declaration"},
    "ruby": {"method"},
    "swift": {
        "function_declaration",
        "initializer_declaration",
        "deinitializer_declaration",
    },
    "kotlin": {"function_declaration", "secondary_constructor"},
    "scala": {"function_definition"},
    "shell": {"function_definition"},
    "sql": {"create_function_statement", "create_procedure_statement"},
}

CLASS_NODE_TYPES_BY_LANGUAGE = {
    "python": {"class_definition"},
    "javascript": {"class_declaration", "class"},
    "typescript": {"class_declaration", "class"},
    "java": {"class_declaration", "record_declaration", "interface_declaration"},
    "go": {"type_declaration"},
    "rust": {"struct_item", "enum_item", "trait_item", "impl_item"},
    "csharp": {"class_declaration", "struct_declaration", "interface_declaration"},
    "php": {"class_declaration", "interface_declaration", "trait_declaration"},
    "ruby": {"class", "module"},
    "swift": {"class_declaration", "struct_declaration", "protocol_declaration", "actor_declaration"},
    "kotlin": {"class_declaration", "object_declaration", "interface_declaration"},
    "scala": {"class_definition", "object_definition", "trait_definition"},
}

IDENTIFIER_NODE_TYPES = {
    "identifier",
    "property_identifier",
    "field_identifier",
    "type_identifier",
    "simple_identifier",
    "name",
    "constant",
    "namespace_identifier",
}

SYMBOL_NAME_NODE_TYPES = (
    "identifier",
    "property_identifier",
    "field_identifier",
    "type_identifier",
    "simple_identifier",
    "name",
)

PARAMETER_CONTAINER_TYPES = {
    "parameters",
    "formal_parameters",
    "parameter_list",
    "parameter_clause",
    "arguments",
}

PARAMETER_BINDING_CONTAINER_TYPES = {
    "parameters",
    "formal_parameters",
    "parameter_list",
    "parameter_clause",
    "method_parameters",
}

LOCAL_BINDING_FIELD_NAMES = (
    "name",
    "left",
    "pattern",
    "alias",
    "target",
)

IMPORT_NODE_TYPE_MARKERS = (
    "import",
    "using",
    "include",
    "require",
)

LOCAL_VARIABLE_NODE_TYPE_MARKERS = (
    "assignment",
    "declaration",
    "declarator",
    "parameter",
    "pattern",
    "for",
    "catch",
    "except",
    "spec",
    "with",
)

CONTROL_FLOW_NODE_TYPE_TAGS = (
    ("if_statement", "if"),
    ("if_expression", "if"),
    ("conditional_expression", "if"),
    ("for_statement", "loop"),
    ("for_in_statement", "loop"),
    ("while_statement", "loop"),
    ("do_statement", "loop"),
    ("loop_expression", "loop"),
    ("foreach_statement", "loop"),
    ("try_statement", "try"),
    ("catch_clause", "try"),
    ("except_clause", "try"),
    ("match_statement", "match"),
    ("switch_statement", "match"),
    ("switch_expression", "match"),
    ("async_function", "async"),
    ("await_expression", "async"),
    ("yield_expression", "yield"),
)

STRUCTURE_NODE_CATEGORIES = (
    ("class", "class"),
    ("function", "function"),
    ("method", "function"),
    ("parameter", "params"),
    ("assignment", "assign"),
    ("declaration", "declare"),
    ("binary", "binary_op"),
    ("unary", "unary_op"),
    ("call", "call"),
    ("return", "return"),
    ("if", "if"),
    ("for", "loop"),
    ("while", "loop"),
    ("loop", "loop"),
    ("try", "try"),
    ("catch", "try"),
    ("match", "match"),
    ("switch", "match"),
    ("await", "async"),
    ("async", "async"),
    ("yield", "yield"),
)

COMMENT_MARKERS = (
    "auto-generated",
    "autogenerated",
    "generated by",
    "generated file",
    "do not edit",
)

COMMON_RESERVED_WORDS = {
    *keyword.kwlist,
    "true",
    "false",
    "null",
    "nil",
    "none",
    "self",
    "cls",
    "this",
    "super",
    "new",
    "def",
    "class",
    "return",
    "func",
    "interface",
    "struct",
    "enum",
    "trait",
    "module",
    "package",
    "import",
    "from",
    "as",
    "async",
    "await",
    "yield",
    "try",
    "catch",
    "except",
    "finally",
    "if",
    "else",
    "elif",
    "for",
    "while",
    "switch",
    "case",
    "match",
    "break",
    "continue",
    "pass",
    "lambda",
    "with",
    "function",
    "throw",
    "typeof",
    "instanceof",
    "delete",
    "default",
    "export",
    "extends",
    "implements",
    "namespace",
    "public",
    "private",
    "protected",
    "internal",
    "static",
    "final",
    "const",
    "var",
    "let",
    "void",
    "int",
    "float",
    "double",
    "bool",
    "boolean",
    "string",
}

PYTHON_BUILTIN_SYMBOLS = {
    name for name in dir(builtins) if name and not name.startswith("_")
}

JAVASCRIPT_COMMON_GLOBALS = {
    "Array",
    "Boolean",
    "Date",
    "decodeURIComponent",
    "encodeURIComponent",
    "Error",
    "Intl",
    "JSON",
    "Map",
    "Math",
    "Number",
    "Object",
    "Promise",
    "RegExp",
    "Set",
    "String",
    "URL",
    "URLSearchParams",
    "clearInterval",
    "clearTimeout",
    "console",
    "exports",
    "isFinite",
    "isNaN",
    "module",
    "parseFloat",
    "parseInt",
    "require",
    "setInterval",
    "setTimeout",
}

RUBY_COMMON_SYMBOLS = {
    "File",
    "puts",
    "print",
    "p",
    "open",
    "require",
    "load",
    "include",
    "extend",
    "attr_reader",
    "attr_writer",
    "attr_accessor",
    "to_i",
    "to_s",
    "split",
    "join",
    "map",
    "each",
    "end",
    "do",
    "then",
    "elsif",
    "unless",
    "begin",
}

PHP_COMMON_SYMBOLS = {
    "die",
    "echo",
    "empty",
    "isset",
    "print",
    "session_start",
}

SHELL_COMMON_SYMBOLS = {
    "cat",
    "done",
    "do",
    "echo",
    "exit",
    "fi",
    "function",
    "grep",
    "kubectl",
    "read",
    "return",
    "rm",
    "then",
    "test",
    "yq",
}

IDENTIFIER_RE = re.compile(r"\b[A-Za-z_][A-Za-z0-9_]*\b")
IDENTIFIER_TEXT_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")

OPERATOR_TOKEN_MAP = (
    ("==", "eq"),
    ("!=", "neq"),
    ("<=", "lte"),
    (">=", "gte"),
    ("&&", "and"),
    ("||", "or"),
    ("=>", "arrow"),
    ("->", "member"),
    ("+", "add"),
    ("-", "sub"),
    ("*", "mul"),
    ("/", "div"),
    ("%", "mod"),
    ("=", "assign"),
    ("<", "lt"),
    (">", "gt"),
)

OPERATOR_SYMBOL_TO_TOKEN = dict(OPERATOR_TOKEN_MAP)
OPERATOR_SYMBOL_PATTERN = re.compile(
    "|".join(
        re.escape(symbol)
        for symbol, _token in sorted(OPERATOR_TOKEN_MAP, key=lambda item: len(item[0]), reverse=True)
    )
)

SIGNIFICANT_NODE_SKIP_TYPES = {
    "comment",
    "identifier",
    "property_identifier",
    "field_identifier",
    "type_identifier",
    "simple_identifier",
    "name",
    "block",
    "statement_block",
    "modifier",
    "modifiers",
    "primitive_type",
    "predefined_type",
    "type_annotation",
    "array_rank_specifier",
    "dimensions",
    "string_content",
    "string_fragment",
    "string_start",
    "string_end",
    "escape_sequence",
}

STRING_PREFIX_CHARS = frozenset("rRuUbBfF")
CALL_LIKE_NODE_TYPES = {
    "call",
    "call_expression",
    "command",
    "function_call_expression",
    "invocation_expression",
    "member_call_expression",
    "method_invocation",
}
CALL_FIELD_NAMES = (
    "function",
    "callee",
    "callable",
    "name",
)
PARENT_SYMBOL_FIELD_NAME_GROUPS = (
    ("name",),
    ("left",),
    ("key",),
    ("property",),
)

FUNCTION_INFERENCE_TOKEN_GROUPS = (
    {"function", "definition"},
    {"function", "declaration"},
    {"function", "item"},
    {"method", "declaration"},
    {"constructor", "declaration"},
    {"local", "function", "statement"},
    {"arrow", "function"},
    {"initializer", "declaration"},
    {"deinitializer", "declaration"},
    {"secondary", "constructor"},
    {"create", "function", "statement"},
    {"create", "procedure", "statement"},
    {"singleton", "method"},
)

CLASS_INFERENCE_TOKEN_GROUPS = (
    {"class", "definition"},
    {"class", "declaration"},
    {"interface", "declaration"},
    {"record", "declaration"},
    {"struct", "declaration"},
    {"struct", "item"},
    {"enum", "item"},
    {"trait", "item"},
    {"impl", "item"},
    {"object", "definition"},
    {"trait", "definition"},
    {"protocol", "declaration"},
    {"actor", "declaration"},
)

TRIVIAL_ONLY_AST_NODE_TYPES = {
    "arrow_function",
    "formal_parameters",
    "function_declarator",
    "function_definition",
    "method_parameters",
    "parameter_list",
    "parameters",
}

TRIVIAL_CLASS_AST_NODE_TYPES = {
    "field_declaration",
    "field_declaration_list",
    "struct_type",
}

SELF_RECURSIVE_CALL_RE = re.compile(r"^(self|cls|this|super)(?:\.|::|->)(?P<name>[A-Za-z_][A-Za-z0-9_]*)$")
INLINE_CALLBACK_ANCESTOR_TYPES = {
    "argument",
    "arguments",
    "argument_list",
    "jsx_expression",
    "jsx_attribute",
}
NAMED_ARROW_PARENT_TYPES = {
    "assignment_expression",
    "field_definition",
    "lexical_declaration",
    "pair",
    "public_field_definition",
    "variable_declaration",
    "variable_declarator",
}
SHELL_VARIABLE_EXPANSION_RE = re.compile(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}|\$([A-Za-z_][A-Za-z0-9_]*)")
SINGLE_QUOTED_STRING_LANGUAGES = {
    "javascript",
    "typescript",
    "php",
    "python",
    "ruby",
    "shell",
    "sql",
}
NON_BINDING_TARGET_NODE_MARKERS = (
    "access",
    "array",
    "attribute",
    "call",
    "element",
    "field_expression",
    "field_identifier",
    "index",
    "member",
    "scope_resolution",
    "selector",
    "subscript",
)


@dataclass(frozen=True, slots=True)
class SymbolSpan:
    chunk_type: str
    symbol_type: str
    symbol_name: str
    param_count: int
    line_start: int
    line_end: int
    start_byte: int
    end_byte: int
    node_type: str


@dataclass(frozen=True, slots=True)
class CodeChunkCandidate:
    chunk_type: str
    symbol_type: str
    symbol_name: str
    param_count: int
    line_start: int
    line_end: int
    node_type: str
    raw_code: str
    normalized_code: str
    anonymized_code: str
    identifier_tokens: list[str]
    call_tokens: list[str]
    operator_tokens: list[str]
    control_flow_tags: list[str]
    structure_signature: str
    ast_node_sequence: list[str]
    raw_hash: str
    normalized_hash: str
    anonymized_hash: str
    validation_status: str


@dataclass(frozen=True, slots=True)
class AnonymizationContext:
    imported_symbols: set[str]
    local_variable_symbols: set[str]
    local_function_symbols: set[str]
    local_class_symbols: set[str]


def build_code_chunk_id(
    *,
    repo_id: str,
    file_path: str,
    chunk_type: str,
    start_line: int,
    end_line: int,
    symbol_name: str,
    chunker_version: str,
) -> str:
    digest_input = "|".join(
        [
            repo_id,
            file_path,
            chunk_type,
            str(start_line),
            str(end_line),
            symbol_name,
            chunker_version,
        ]
    )
    return hashlib.sha1(digest_input.encode("utf-8")).hexdigest()


def _ordered_unique(values: list[str], *, cap: int) -> list[str]:
    normalized_cap = max(0, cap)
    ordered: list[str] = []
    seen: set[str] = set()
    for value in values:
        normalized = str(value or "").strip()
        if not normalized or normalized in seen:
            continue
        seen.add(normalized)
        ordered.append(normalized)
        if normalized_cap and len(ordered) >= normalized_cap:
            break
    return ordered


def _decode_node_text(content_bytes: bytes, node: Node) -> str:
    try:
        return content_bytes[node.start_byte : node.end_byte].decode("utf-8", errors="ignore")
    except Exception:  # noqa: BLE001 - best effort decode only
        return ""


def _contains_generated_marker(raw_code: str) -> bool:
    header = "\n".join(raw_code.splitlines()[:5]).lower()
    return any(marker in header for marker in COMMENT_MARKERS)


def _should_skip_decorated_python_node(language: str, node: Node) -> bool:
    parent = getattr(node, "parent", None)
    if language != "python" or parent is None:
        return False
    node_type = str(node.type or "")
    parent_type = str(parent.type or "")
    if node_type in {"function_definition", "class_definition"} and parent_type == "decorated_definition":
        return True
    return False


def _get_decorated_python_target(node: Node) -> Node | None:
    for child in node.children:
        if not child.is_named:
            continue
        child_type = str(child.type or "")
        if child_type in {"class_definition", "function_definition"}:
            return child
    return None


def _node_type_tokens(node_type: str) -> set[str]:
    return {token for token in re.split(r"[^a-z0-9]+|_", node_type.lower()) if token}


def _node_matches_chunk_type(language: str, node: Node) -> str | None:
    node_type = str(node.type or "")
    if not node_type or not node.is_named:
        return None

    if language == "python" and node_type == "decorated_definition":
        decorated_target = _get_decorated_python_target(node)
        if decorated_target is not None:
            return _node_matches_chunk_type(language, decorated_target)

    function_node_types = FUNCTION_NODE_TYPES_BY_LANGUAGE.get(language, set())
    class_node_types = CLASS_NODE_TYPES_BY_LANGUAGE.get(language, set())

    if node_type in function_node_types:
        return "function"
    if node_type in class_node_types:
        return "class"

    tokens = _node_type_tokens(node_type)
    if any(group.issubset(tokens) for group in FUNCTION_INFERENCE_TOKEN_GROUPS):
        return "function"
    if any(group.issubset(tokens) for group in CLASS_INFERENCE_TOKEN_GROUPS):
        return "class"
    return None


def _extract_symbol_name(content_bytes: bytes, node: Node) -> str:
    if str(node.type or "") == "decorated_definition":
        decorated_target = _get_decorated_python_target(node)
        if decorated_target is not None:
            return _extract_symbol_name(content_bytes, decorated_target)

    declarator_child = _find_child_by_field_names(node, ("declarator",))
    if declarator_child is not None:
        declarator_name = _extract_symbol_name(content_bytes, declarator_child)
        if declarator_name:
            return declarator_name

    direct_name_child = _find_child_by_field_names(node, ("name",))
    if direct_name_child is not None:
        direct_name = _decode_node_text(content_bytes, direct_name_child).strip()
        if direct_name:
            return direct_name

    for child in node.children:
        if not child.is_named:
            continue
        child_type = str(child.type or "")
        lowered_child_type = child_type.lower()
        if (
            child_type in PARAMETER_CONTAINER_TYPES
            or "body" in child_type
            or "block" in child_type
            or "type" in lowered_child_type
            or child_type in {"storage_class_specifier", "visibility_modifier", "modifiers"}
        ):
            continue
        if child_type in SYMBOL_NAME_NODE_TYPES:
            value = _decode_node_text(content_bytes, child).strip()
            if value:
                return value

    current = node
    for _ in range(4):
        parent = getattr(current, "parent", None)
        if parent is None:
            break
        for field_names in PARENT_SYMBOL_FIELD_NAME_GROUPS:
            candidate = _find_child_by_field_names(parent, field_names)
            if candidate is None:
                continue
            if (
                int(candidate.start_byte) == int(current.start_byte)
                and int(candidate.end_byte) == int(current.end_byte)
            ):
                continue
            identifiers = _collect_identifier_texts(content_bytes, candidate)
            if identifiers:
                return identifiers[-1]
            candidate_text = _decode_node_text(content_bytes, candidate).strip()
            if candidate_text:
                identifier_matches = IDENTIFIER_TEXT_RE.findall(candidate_text)
                if identifier_matches:
                    return identifier_matches[-1]
        current = parent

    return ""


def _estimate_param_count(raw_code: str) -> int:
    header_lines = raw_code.splitlines()[:3]
    header = " ".join(line.strip() for line in header_lines)
    match = re.search(r"\((.*?)\)", header)
    if not match:
        return 0
    inside = match.group(1).strip()
    if not inside:
        return 0
    parts = [chunk.strip() for chunk in inside.split(",")]
    return len([part for part in parts if part])


def _collect_identifier_texts(content_bytes: bytes, node: Node) -> list[str]:
    tokens: list[str] = []
    stack = [node]
    while stack:
        current = stack.pop()
        if not current.is_named:
            continue
        current_type = str(current.type or "")
        if current_type in IDENTIFIER_NODE_TYPES:
            token = _decode_node_text(content_bytes, current).strip()
            if token:
                tokens.append(token)
        stack.extend(reversed(list(current.children)))
    return tokens


def _ordered_unique_set(values: list[str]) -> set[str]:
    return {value for value in _ordered_unique(values, cap=0) if value}


def _find_child_by_field_names(node: Node, field_names: tuple[str, ...]) -> Node | None:
    child_by_field_name = getattr(node, "child_by_field_name", None)
    if not callable(child_by_field_name):
        return None
    for field_name in field_names:
        child = child_by_field_name(field_name)
        if child is not None:
            return child
    return None


def _find_parameter_container(node: Node) -> Node | None:
    for child in node.children:
        if not child.is_named:
            continue
        child_type = str(child.type or "")
        if child_type in PARAMETER_BINDING_CONTAINER_TYPES:
            return child
    return None


def _is_import_like_node(node_type: str) -> bool:
    lowered = node_type.lower()
    return any(marker in lowered for marker in IMPORT_NODE_TYPE_MARKERS)


def _is_local_variable_like_node(node_type: str) -> bool:
    lowered = node_type.lower()
    return any(marker in lowered for marker in LOCAL_VARIABLE_NODE_TYPE_MARKERS)


def _collect_imported_symbols(content_bytes: bytes, node: Node) -> set[str]:
    imported_symbols: set[str] = set()
    stack = [node]
    while stack:
        current = stack.pop()
        if not current.is_named:
            continue
        current_type = str(current.type or "")
        if _is_import_like_node(current_type):
            alias_child = _find_child_by_field_names(current, ("alias", "name"))
            if alias_child is not None:
                imported_symbols.update(_ordered_unique_set(_collect_identifier_texts(content_bytes, alias_child)))
            else:
                imported_symbols.update(_ordered_unique_set(_collect_identifier_texts(content_bytes, current)))
        stack.extend(reversed(list(current.children)))
    return imported_symbols


def _collect_binding_identifier_texts(content_bytes: bytes, node: Node) -> list[str]:
    tokens: list[str] = []
    stack = [node]
    while stack:
        current = stack.pop()
        if not current.is_named:
            continue
        current_type = str(current.type or "")
        lowered_type = current_type.lower()
        if "type" in lowered_type:
            continue
        if current_type in IDENTIFIER_NODE_TYPES:
            token = _decode_node_text(content_bytes, current).strip()
            if token:
                tokens.append(token)
            continue
        stack.extend(reversed(list(current.children)))
    return tokens


def _allows_assignment_bindings(language: str) -> bool:
    return language in {"php", "python", "ruby", "shell"}


def _is_assignment_expression_like(node_type: str) -> bool:
    lowered = node_type.lower()
    return "assignment" in lowered and "declaration" not in lowered and "declarator" not in lowered


def _is_plain_binding_target(node: Node) -> bool:
    node_type = str(node.type or "").lower()
    if any(marker in node_type for marker in NON_BINDING_TARGET_NODE_MARKERS):
        return False
    return True


def _collect_local_binding_symbols(content_bytes: bytes, node: Node, language: str) -> set[str]:
    local_symbols: set[str] = set()
    allow_assignment_bindings = _allows_assignment_bindings(language)
    stack = [node]
    while stack:
        current = stack.pop()
        if not current.is_named:
            continue
        current_type = str(current.type or "")
        if _is_import_like_node(current_type):
            stack.extend(reversed(list(current.children)))
            continue

        binding_child = _find_child_by_field_names(current, LOCAL_BINDING_FIELD_NAMES)
        lowered_type = current_type.lower()
        if binding_child is not None and (
            _is_local_variable_like_node(current_type) or "parameter" in lowered_type
        ):
            if _is_assignment_expression_like(current_type):
                if not allow_assignment_bindings or not _is_plain_binding_target(binding_child):
                    stack.extend(reversed(list(current.children)))
                    continue
            local_symbols.update(_ordered_unique_set(_collect_binding_identifier_texts(content_bytes, binding_child)))
        elif binding_child is None and ("spec" in lowered_type or current_type in {"with_item"}):
            local_symbols.update(_ordered_unique_set(_collect_binding_identifier_texts(content_bytes, current)))

        parameter_child = _find_parameter_container(current)
        if parameter_child is not None:
            local_symbols.update(
                _ordered_unique_set(_collect_binding_identifier_texts(content_bytes, parameter_child))
            )

        stack.extend(reversed(list(current.children)))
    return local_symbols


def _collect_nested_symbol_names(content_bytes: bytes, node: Node, language: str) -> tuple[set[str], set[str]]:
    function_symbols: set[str] = set()
    class_symbols: set[str] = set()
    stack = list(reversed(list(node.children)))
    while stack:
        current = stack.pop()
        if not current.is_named:
            continue
        chunk_type = _node_matches_chunk_type(language, current)
        if chunk_type is not None and not _should_skip_decorated_python_node(language, current):
            if (
                language in {"javascript", "typescript"}
                and chunk_type == "function"
                and str(current.type or "") == "arrow_function"
                and _is_inline_callback_arrow_function(current)
            ):
                stack.extend(reversed(list(current.children)))
                continue
            symbol_name = _extract_symbol_name(content_bytes, current).strip()
            if symbol_name:
                if chunk_type == "function":
                    function_symbols.add(symbol_name)
                elif chunk_type == "class":
                    class_symbols.add(symbol_name)
        stack.extend(reversed(list(current.children)))
    return function_symbols, class_symbols


def _build_anonymization_context(content_bytes: bytes, node: Node, language: str) -> AnonymizationContext:
    imported_symbols = _collect_imported_symbols(content_bytes, node)
    local_variable_symbols = _collect_local_binding_symbols(content_bytes, node, language)
    local_function_symbols, local_class_symbols = _collect_nested_symbol_names(content_bytes, node, language)
    local_variable_symbols -= imported_symbols
    local_function_symbols -= imported_symbols
    local_class_symbols -= imported_symbols
    return AnonymizationContext(
        imported_symbols=imported_symbols,
        local_variable_symbols=local_variable_symbols,
        local_function_symbols=local_function_symbols,
        local_class_symbols=local_class_symbols,
    )


def _collect_comment_ranges(node: Node) -> list[tuple[int, int]]:
    ranges: list[tuple[int, int]] = []
    stack = [node]
    while stack:
        current = stack.pop()
        node_type = str(current.type or "")
        if "comment" in node_type:
            ranges.append((current.start_byte, current.end_byte))
        stack.extend(reversed(list(current.children)))
    ranges.sort()
    return ranges


def _remove_comment_ranges(raw_bytes: bytes, comment_ranges: list[tuple[int, int]], start_byte: int) -> bytes:
    if not comment_ranges:
        return raw_bytes

    pieces: list[bytes] = []
    cursor = start_byte
    end_byte = start_byte + len(raw_bytes)
    for comment_start, comment_end in comment_ranges:
        bounded_start = max(start_byte, min(comment_start, end_byte))
        bounded_end = max(start_byte, min(comment_end, end_byte))
        if bounded_start > cursor:
            pieces.append(raw_bytes[cursor - start_byte : bounded_start - start_byte])
        cursor = max(cursor, bounded_end)
    if cursor < end_byte:
        pieces.append(raw_bytes[cursor - start_byte : end_byte - start_byte])
    return b"".join(pieces)


def _normalize_code(raw_code: str, raw_bytes: bytes, node: Node) -> str:
    comment_ranges = _collect_comment_ranges(node)
    normalized_bytes = _remove_comment_ranges(raw_bytes, comment_ranges, node.start_byte)
    normalized_text = normalized_bytes.decode("utf-8", errors="ignore")

    collapsed_lines: list[str] = []
    previous_blank = False
    for line in normalized_text.splitlines():
        compact_line = re.sub(r"[ \t]+", " ", line.rstrip())
        if not compact_line.strip():
            if previous_blank:
                continue
            collapsed_lines.append("")
            previous_blank = True
            continue
        collapsed_lines.append(compact_line)
        previous_blank = False

    return "\n".join(collapsed_lines).strip()


def _collect_identifier_tokens(content_bytes: bytes, node: Node, *, cap: int) -> list[str]:
    tokens: list[str] = []
    stack = [node]
    while stack:
        current = stack.pop()
        current_type = str(current.type or "")
        if current_type in IDENTIFIER_NODE_TYPES:
            token = _decode_node_text(content_bytes, current).strip()
            if token:
                tokens.append(token)
        stack.extend(reversed([child for child in current.children if child.is_named]))
    return _ordered_unique(tokens, cap=cap)


def _is_call_like_node(node_type: str) -> bool:
    lowered = node_type.lower()
    if lowered in CALL_LIKE_NODE_TYPES:
        return True
    return "call" in lowered and "callback" not in lowered


def _normalize_call_target_text(raw_text: str) -> str:
    normalized = re.sub(r"\s+", "", raw_text.strip())
    if not normalized:
        return ""

    normalized = re.sub(r"\[[^\[\]]*\]", "", normalized)
    normalized = re.sub(r"`[^`]*`", "", normalized)

    previous = None
    while previous != normalized:
        previous = normalized
        normalized = re.sub(r"\([^()]*\)", "", normalized)

    if normalized.startswith("new") and len(normalized) > 3 and normalized[3].isalpha():
        normalized = normalized[3:]

    if normalized.startswith("$."):
        identifiers = IDENTIFIER_TEXT_RE.findall(normalized)
        return "$." + ".".join(identifiers)
    if "." in normalized:
        identifiers = IDENTIFIER_TEXT_RE.findall(normalized)
        return ".".join(identifiers)
    if "::" in normalized:
        identifiers = IDENTIFIER_TEXT_RE.findall(normalized)
        return "::".join(identifiers)
    if "->" in normalized:
        identifiers = IDENTIFIER_TEXT_RE.findall(normalized)
        return "->".join(identifiers)

    identifier_matches = IDENTIFIER_TEXT_RE.findall(normalized)
    if not identifier_matches:
        return ""
    if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", normalized):
        return normalized
    return identifier_matches[-1]


def _extract_shell_command_name(content_bytes: bytes, node: Node) -> str:
    command_name_child = _find_child_by_field_names(node, ("name", "command"))
    if command_name_child is not None:
        return _normalize_call_target_text(_decode_node_text(content_bytes, command_name_child))

    for child in node.children:
        if not child.is_named:
            continue
        child_type = str(child.type or "")
        if child_type == "command_name":
            return _normalize_call_target_text(_decode_node_text(content_bytes, child))
    return ""


def _extract_ruby_call_token(raw_text: str) -> str:
    normalized = raw_text.strip()
    if not normalized:
        return ""

    normalized = normalized.split("{", 1)[0].strip()
    normalized = re.split(r"\bdo\b", normalized, maxsplit=1)[0].strip()

    dotted_match = re.match(
        r"((?:self|[A-Za-z_][A-Za-z0-9_]*)(?:(?:\.|::)[A-Za-z_][A-Za-z0-9_]*[!?=]?)*)",
        normalized,
    )
    if dotted_match:
        return dotted_match.group(1)

    bare_match = re.match(r"([A-Za-z_][A-Za-z0-9_]*[!?=]?)", normalized)
    if bare_match:
        return bare_match.group(1)

    return ""


def _extract_call_token_from_node(content_bytes: bytes, node: Node, *, language: str) -> str:
    raw_text = _decode_node_text(content_bytes, node)
    if language == "ruby":
        ruby_token = _extract_ruby_call_token(raw_text)
        if ruby_token:
            return ruby_token
    if language == "shell":
        shell_token = _extract_shell_command_name(content_bytes, node)
        if shell_token:
            return shell_token
    raw_token = _normalize_call_target_text(raw_text)
    if raw_token and (
        "." in raw_token or "::" in raw_token or "->" in raw_token or raw_text.lstrip().startswith("new ")
    ):
        return raw_token

    callee = _find_child_by_field_names(node, CALL_FIELD_NAMES)
    if callee is None:
        named_children = [child for child in node.children if child.is_named]
        if not named_children:
            return raw_token
        callee = named_children[0]
    callee_token = _normalize_call_target_text(_decode_node_text(content_bytes, callee))
    return callee_token or raw_token


def _collect_call_tokens(content_bytes: bytes, node: Node, *, language: str, cap: int) -> list[str]:
    tokens: list[str] = []
    stack = [node]
    while stack:
        current = stack.pop()
        if not current.is_named:
            continue
        current_type = str(current.type or "")
        if _is_call_like_node(current_type):
            token = _extract_call_token_from_node(content_bytes, current, language=language)
            if token and token.lower() not in COMMON_RESERVED_WORDS:
                tokens.append(token)
        stack.extend(reversed([child for child in current.children if child.is_named]))
    return _ordered_unique(tokens, cap=cap)

def _extract_operator_tokens_from_gap(gap_text: str) -> list[str]:
    if not gap_text.strip():
        return []

    tokens: list[str] = []
    seen: set[str] = set()
    for match in OPERATOR_SYMBOL_PATTERN.finditer(gap_text):
        token = OPERATOR_SYMBOL_TO_TOKEN.get(match.group(0))
        if token and token not in seen:
            tokens.append(token)
            seen.add(token)

    lowered_gap = f" {gap_text.lower()} "
    for keyword_token, token in ((" and ", "and"), (" or ", "or"), (" not ", "not")):
        if keyword_token in lowered_gap and token not in seen:
            tokens.append(token)
            seen.add(token)
    return tokens


def _collect_operator_tokens(content_bytes: bytes, node: Node) -> list[str]:
    ordered: list[str] = []
    seen: set[str] = set()

    stack = [node]
    while stack:
        current = stack.pop()
        if not current.is_named:
            continue

        current_type = str(current.type or "").lower()
        named_children = [child for child in current.children if child.is_named]

        if "assignment" in current_type and "assign" not in seen:
            ordered.append("assign")
            seen.add("assign")

        if len(named_children) >= 2 and (
            "binary" in current_type
            or "comparison" in current_type
            or "member" in current_type
            or "selector" in current_type
            or "attribute" == current_type
            or "qualified_identifier" == current_type
        ):
            previous_child = named_children[0]
            for child in named_children[1:]:
                gap_text = content_bytes[previous_child.end_byte : child.start_byte].decode(
                    "utf-8",
                    errors="ignore",
                )
                for token in _extract_operator_tokens_from_gap(gap_text):
                    if token not in seen:
                        ordered.append(token)
                        seen.add(token)
                previous_child = child

        if "unary" in current_type and named_children:
            first_child = named_children[0]
            prefix_text = content_bytes[current.start_byte : first_child.start_byte].decode(
                "utf-8",
                errors="ignore",
            )
            for token in _extract_operator_tokens_from_gap(prefix_text):
                if token not in seen:
                    ordered.append(token)
                    seen.add(token)

        stack.extend(reversed(named_children))
    return ordered


def _collect_ast_node_sequence(node: Node, *, cap: int) -> list[str]:
    sequence: list[str] = []
    stack = [node]
    while stack and len(sequence) < max(1, cap):
        current = stack.pop()
        if not current.is_named:
            continue
        current_type = str(current.type or "")
        if not current_type or current_type in SIGNIFICANT_NODE_SKIP_TYPES:
            stack.extend(reversed([child for child in current.children if child.is_named]))
            continue
        sequence.append(current_type)
        stack.extend(reversed([child for child in current.children if child.is_named]))
    return sequence


def _build_structure_signature(chunk_type: str, ast_node_sequence: list[str]) -> str:
    parts = [chunk_type]
    for node_type in ast_node_sequence:
        lowered = node_type.lower()
        node_tokens = {token for token in re.split(r"[^a-z0-9]+|_", lowered) if token}
        for marker, category in STRUCTURE_NODE_CATEGORIES:
            if any(token == marker or token.rstrip("s") == marker for token in node_tokens) and category not in parts:
                parts.append(category)
                break
        if len(parts) >= 6:
            break
    return "|".join(parts)


def _collect_control_flow_tags(
    *,
    ast_node_sequence: list[str],
    symbol_name: str,
    call_tokens: list[str],
) -> list[str]:
    tags: list[str] = []
    seen: set[str] = set()

    lowered_node_types = [node_type.lower() for node_type in ast_node_sequence]
    for node_type, tag in CONTROL_FLOW_NODE_TYPE_TAGS:
        if any(node_type in lowered for lowered in lowered_node_types) and tag not in seen:
            tags.append(tag)
            seen.add(tag)

    is_recursive = False
    if symbol_name:
        for token in call_tokens:
            if token == symbol_name:
                is_recursive = True
                break
            recursive_match = SELF_RECURSIVE_CALL_RE.match(token)
            if recursive_match and recursive_match.group("name") == symbol_name:
                is_recursive = True
                break

    if is_recursive:
        if "recursion" not in seen:
            tags.append("recursion")
            seen.add("recursion")

    if not tags:
        return ["none"]
    return tags


def _looks_like_external_pascal_symbol(token: str, *, local_symbols: set[str]) -> bool:
    if token in local_symbols:
        return False
    if not token or "_" in token:
        return False
    if not token[0].isupper():
        return False
    return any(char.islower() for char in token[1:])


def _iter_string_ranges(code: str, *, language: str) -> list[tuple[int, int]]:
    ranges: list[tuple[int, int]] = []
    index = 0
    code_length = len(code)
    allow_single_quote = language in SINGLE_QUOTED_STRING_LANGUAGES

    while index < code_length:
        current = code[index]
        if current not in {'"', "`"} and not (current == "'" and allow_single_quote):
            index += 1
            continue

        start = index
        if current in {"'", '"'}:
            prefix_start = index
            while prefix_start > 0 and code[prefix_start - 1] in STRING_PREFIX_CHARS:
                prefix_start -= 1
            if prefix_start < index:
                before_prefix = code[prefix_start - 1] if prefix_start > 0 else ""
                if not before_prefix or (not before_prefix.isalnum() and before_prefix != "_"):
                    start = prefix_start

        triple_quoted = (
            current in {"'", '"'}
            and index + 2 < code_length
            and code[index + 1] == current
            and code[index + 2] == current
        )
        cursor = index + (3 if triple_quoted else 1)

        if current == "`":
            while cursor < code_length:
                if code[cursor] == "\\":
                    cursor += 2
                    continue
                if code[cursor] == "`":
                    cursor += 1
                    break
                cursor += 1
        elif triple_quoted:
            while cursor < code_length:
                if code[cursor] == "\\":
                    cursor += 2
                    continue
                if (
                    cursor + 2 < code_length
                    and code[cursor] == current
                    and code[cursor + 1] == current
                    and code[cursor + 2] == current
                ):
                    cursor += 3
                    break
                cursor += 1
        else:
            while cursor < code_length:
                if code[cursor] == "\\":
                    cursor += 2
                    continue
                if code[cursor] == current:
                    cursor += 1
                    break
                cursor += 1

        ranges.append((start, min(cursor, code_length)))
        index = max(cursor, index + 1)

    return ranges


def _preserved_symbols_for_language(language: str) -> set[str]:
    normalized_language = str(language or "").strip().lower()
    if normalized_language == "python":
        return set(PYTHON_BUILTIN_SYMBOLS)
    if normalized_language in {"javascript", "typescript"}:
        return set(JAVASCRIPT_COMMON_GLOBALS)
    if normalized_language == "ruby":
        return set(RUBY_COMMON_SYMBOLS)
    if normalized_language == "php":
        return set(PHP_COMMON_SYMBOLS)
    if normalized_language == "shell":
        return set(SHELL_COMMON_SYMBOLS)
    return set()


def _previous_non_whitespace_char(text: str, index: int) -> str:
    cursor = index - 1
    while cursor >= 0 and text[cursor].isspace():
        cursor -= 1
    return text[cursor] if cursor >= 0 else ""


def _previous_non_whitespace_index(text: str, index: int) -> int:
    cursor = index - 1
    while cursor >= 0 and text[cursor].isspace():
        cursor -= 1
    return cursor


def _next_non_whitespace_char(text: str, index: int) -> str:
    cursor = index
    text_length = len(text)
    while cursor < text_length and text[cursor].isspace():
        cursor += 1
    return text[cursor] if cursor < text_length else ""


def _next_non_whitespace_index(text: str, index: int) -> int:
    cursor = index
    text_length = len(text)
    while cursor < text_length and text[cursor].isspace():
        cursor += 1
    return cursor if cursor < text_length else -1


def _has_member_or_namespace_prefix(text: str, start: int) -> bool:
    if start >= 3 and text[start - 3 : start] == "...":
        return False
    if start >= 2:
        two_char_prefix = text[start - 2 : start]
        if two_char_prefix in {"::", "->"}:
            return True
    return _previous_non_whitespace_char(text, start) in {".", "\\"}


def _is_object_key_or_shorthand_context(text: str, start: int, end: int) -> bool:
    previous_index = _previous_non_whitespace_index(text, start)
    previous_char = text[previous_index] if previous_index >= 0 else ""
    next_char = _next_non_whitespace_char(text, end)
    if previous_char == "{" and previous_index > 0 and text[previous_index - 1] in {"#", "$"}:
        return False
    return previous_char in "{," and next_char == ":"


def _is_named_value_key_context(text: str, start: int, end: int) -> bool:
    previous_index = _previous_non_whitespace_index(text, start)
    previous_char = text[previous_index] if previous_index >= 0 else ""
    next_index = _next_non_whitespace_index(text, end)
    if next_index < 0 or previous_char not in "{(,":
        return False
    if text[next_index : next_index + 2] in {"==", "=>"}:
        return False
    return text[next_index] == "="


def _replace_identifiers_in_segment(
    segment: str,
    *,
    absolute_start: int,
    replace_token: Any,
) -> str:
    parts: list[str] = []
    cursor = 0
    for match in IDENTIFIER_RE.finditer(segment):
        start, end = match.span()
        parts.append(segment[cursor:start])
        parts.append(replace_token(match.group(0), absolute_start + start, absolute_start + end))
        cursor = end
    parts.append(segment[cursor:])
    return "".join(parts)


def _anonymize_interpolated_string_segment(
    *,
    language: str,
    segment: str,
    absolute_start: int,
    replace_token: Any,
) -> str:
    interpolation_pattern: re.Pattern[str] | None = None
    if language == "ruby":
        interpolation_pattern = re.compile(r"#\{([^{}]+)\}")
    elif language == "python" and re.match(r"(?i)^[rubf]*f[rubf]*(['\"]{1,3})", segment):
        interpolation_pattern = re.compile(r"\{([^{}]+)\}")
    elif language in {"javascript", "typescript"} and segment.startswith("`"):
        interpolation_pattern = re.compile(r"\$\{([^{}]+)\}")

    if interpolation_pattern is None:
        return segment

    parts: list[str] = []
    cursor = 0
    for match in interpolation_pattern.finditer(segment):
        inner_start, inner_end = match.span(1)
        parts.append(segment[cursor:inner_start])
        parts.append(
            _replace_identifiers_in_segment(
                segment[inner_start:inner_end],
                absolute_start=absolute_start + inner_start,
                replace_token=replace_token,
            )
        )
        cursor = inner_end
    parts.append(segment[cursor:])
    return "".join(parts)


def _split_string_literal_segment(segment: str) -> tuple[str, str, str, str] | None:
    if not segment:
        return None

    quote_index = 0
    while quote_index < len(segment) and segment[quote_index] in STRING_PREFIX_CHARS:
        quote_index += 1
    if quote_index >= len(segment):
        return None

    quote_char = segment[quote_index]
    if quote_char == "`":
        if len(segment) < quote_index + 2:
            return None
        return segment[:quote_index], "`", segment[quote_index + 1 : -1], "`"

    if quote_char not in {"'", '"'}:
        return None

    triple = segment[quote_index : quote_index + 3] == quote_char * 3
    opener = quote_char * (3 if triple else 1)
    opener_len = len(opener)
    if len(segment) < quote_index + opener_len * 2:
        return None
    prefix = segment[:quote_index]
    content_start = quote_index + opener_len
    content_end = len(segment) - opener_len
    return prefix, opener, segment[content_start:content_end], opener


def _normalize_string_fragment(
    fragment: str,
    *,
    string_replacements: dict[str, str],
    next_string_index: list[int],
) -> str:
    replacement = string_replacements.get(fragment)
    if replacement is not None:
        return replacement

    replacement = f"STR_{next_string_index[0]}"
    next_string_index[0] += 1
    string_replacements[fragment] = replacement
    return replacement


def _normalize_string_literal_segment(
    *,
    language: str,
    segment: str,
    absolute_start: int,
    replace_token: Any,
    string_replacements: dict[str, str],
    next_string_index: list[int],
) -> str:
    parsed = _split_string_literal_segment(segment)
    if parsed is None:
        return segment

    prefix, opener, content, closer = parsed
    if language == "shell" and "$" in content:
        parts: list[str] = []
        cursor = 0
        inner_offset = len(prefix) + len(opener)
        for match in SHELL_VARIABLE_EXPANSION_RE.finditer(content):
            literal_fragment = content[cursor : match.start()]
            if literal_fragment:
                parts.append(
                    _normalize_string_fragment(
                        literal_fragment,
                        string_replacements=string_replacements,
                        next_string_index=next_string_index,
                    )
                )

            if match.group(1) is not None:
                token_start, token_end = match.span(1)
                parts.append("${")
                parts.append(
                    _replace_identifiers_in_segment(
                        match.group(1),
                        absolute_start=absolute_start + inner_offset + token_start,
                        replace_token=replace_token,
                    )
                )
                parts.append("}")
            else:
                token_start, token_end = match.span(2)
                parts.append("$")
                parts.append(
                    _replace_identifiers_in_segment(
                        match.group(2),
                        absolute_start=absolute_start + inner_offset + token_start,
                        replace_token=replace_token,
                    )
                )
            cursor = match.end()

        if parts:
            trailing_fragment = content[cursor:]
            if trailing_fragment:
                parts.append(
                    _normalize_string_fragment(
                        trailing_fragment,
                        string_replacements=string_replacements,
                        next_string_index=next_string_index,
                    )
                )
            return f"{prefix}{opener}{''.join(parts)}{closer}"

    interpolation_pattern: re.Pattern[str] | None = None
    if language == "ruby":
        interpolation_pattern = re.compile(r"#\{([^{}]+)\}")
    elif language == "python" and re.match(r"(?i)^[rubf]*f[rubf]*(['\"]{1,3})", segment):
        interpolation_pattern = re.compile(r"\{([^{}]+)\}")
    elif language in {"javascript", "typescript"} and opener == "`":
        interpolation_pattern = re.compile(r"\$\{([^{}]+)\}")

    if interpolation_pattern is None:
        replacement = _normalize_string_fragment(
            content,
            string_replacements=string_replacements,
            next_string_index=next_string_index,
        )
        return f"{prefix}{opener}{replacement}{closer}"

    parts: list[str] = []
    cursor = 0
    inner_offset = len(prefix) + len(opener)
    for match in interpolation_pattern.finditer(content):
        literal_fragment = content[cursor : match.start()]
        if literal_fragment:
            parts.append(
                _normalize_string_fragment(
                    literal_fragment,
                    string_replacements=string_replacements,
                    next_string_index=next_string_index,
                )
            )
        expression_start, expression_end = match.span(1)
        parts.append(content[match.start() : expression_start])
        parts.append(
            _replace_identifiers_in_segment(
                content[expression_start:expression_end],
                absolute_start=absolute_start + inner_offset + expression_start,
                replace_token=replace_token,
            )
        )
        parts.append(content[expression_end : match.end()])
        cursor = match.end()

    trailing_fragment = content[cursor:]
    if trailing_fragment:
        parts.append(
            _normalize_string_fragment(
                trailing_fragment,
                string_replacements=string_replacements,
                next_string_index=next_string_index,
            )
        )
    return f"{prefix}{opener}{''.join(parts)}{closer}"


def _anonymize_class_code(normalized_code: str, symbol_name: str) -> str:
    if not symbol_name:
        return normalized_code

    replacement_done = False

    def replace_first(match: re.Match[str]) -> str:
        nonlocal replacement_done
        token = match.group(0)
        if replacement_done or token != symbol_name:
            return token
        replacement_done = True
        return "CLASS_0"

    return IDENTIFIER_RE.sub(replace_first, normalized_code)


def _split_top_level_csv(text: str) -> list[str]:
    if not text.strip():
        return []

    parts: list[str] = []
    current: list[str] = []
    depths = {"(": 0, "[": 0, "{": 0, "<": 0}
    openers = tuple(depths.keys())
    closing_to_opening = {
        ")": "(",
        "]": "[",
        "}": "{",
        ">": "<",
    }
    string_delimiter = ""
    escape = False

    for char in text:
        if string_delimiter:
            current.append(char)
            if escape:
                escape = False
                continue
            if char == "\\":
                escape = True
                continue
            if char == string_delimiter:
                string_delimiter = ""
            continue

        if char in {"'", '"', "`"}:
            string_delimiter = char
            current.append(char)
            continue

        if char in openers:
            depths[char] += 1
            current.append(char)
            continue

        if char in closing_to_opening:
            opening = closing_to_opening[char]
            if depths[opening] > 0:
                depths[opening] -= 1
            current.append(char)
            continue

        if char == "," and not any(depths.values()):
            part = "".join(current).strip()
            if part:
                parts.append(part)
            current = []
            continue

        current.append(char)

    trailing = "".join(current).strip()
    if trailing:
        parts.append(trailing)
    return parts


def _extract_js_ts_header_parameter_names(normalized_code: str) -> set[str]:
    if not normalized_code.strip():
        return set()

    header_lines = normalized_code.splitlines()[:4]
    header_text = " ".join(line.strip() for line in header_lines if line.strip())
    if not header_text:
        return set()

    header_end = len(header_text)
    arrow_index = header_text.find("=>")
    brace_index = header_text.find("{")
    if arrow_index >= 0:
        header_end = min(header_end, arrow_index)
    if brace_index >= 0:
        header_end = min(header_end, brace_index)
    header_text = header_text[:header_end]

    open_index = header_text.find("(")
    close_index = header_text.rfind(")")
    if open_index < 0 or close_index <= open_index:
        return set()

    parameter_names: set[str] = set()
    parameter_text = header_text[open_index + 1 : close_index]
    for part in _split_top_level_csv(parameter_text):
        cleaned = re.sub(r"^\.\.\.", "", part.strip())
        cleaned = cleaned.split("=", 1)[0].strip()
        cleaned = cleaned.split(":", 1)[0].strip()
        if re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", cleaned):
            parameter_names.add(cleaned)
    return parameter_names


def _canonicalize_named_arrow_function_code(anonymized_code: str, *, node_type: str, symbol_name: str) -> str:
    if node_type != "arrow_function" or not symbol_name or not anonymized_code.strip():
        return anonymized_code

    stripped = anonymized_code.lstrip()
    if stripped.startswith(("const FUNC_0 =", "let FUNC_0 =", "var FUNC_0 =")):
        return anonymized_code
    if not (
        stripped.startswith("(")
        or stripped.startswith("async ")
        or re.match(r"^[A-Za-z_$][A-Za-z0-9_$]*\s*=>", stripped)
    ):
        return anonymized_code

    leading = anonymized_code[: len(anonymized_code) - len(stripped)]
    return f"{leading}const FUNC_0 = {stripped}"


def _anonymize_code(
    *,
    language: str,
    normalized_code: str,
    symbol_name: str,
    chunk_type: str,
    call_tokens: list[str],
    imported_symbols: set[str],
    local_variable_symbols: set[str],
    local_function_symbols: set[str],
    local_class_symbols: set[str],
) -> str:
    if chunk_type == "class":
        return _anonymize_class_code(normalized_code, symbol_name)

    preserve_exact: set[str] = set(COMMON_RESERVED_WORDS)
    preserve_exact.update(_preserved_symbols_for_language(language))
    preserve_exact.update(imported_symbols)
    local_symbols = local_variable_symbols | local_function_symbols | local_class_symbols
    for token in call_tokens:
        parts = [part for part in token.split(".") if part]
        if not parts:
            continue
        if len(parts) == 1:
            continue
        if parts[0] not in local_symbols:
            preserve_exact.add(parts[0])
        preserve_exact.update(parts[1:])
    preserve_lowered = {token.lower() for token in preserve_exact}

    replacements: dict[str, str] = {}
    string_replacements: dict[str, str] = {}
    next_string_index = [0]
    next_var_index = 0
    next_function_index = 1
    next_class_index = 1
    symbol_alias = "CLASS_0" if chunk_type == "class" else "FUNC_0"

    def replace_token(token: str, start: int, end: int) -> str:
        nonlocal next_var_index, next_function_index, next_class_index
        lowered = token.lower()
        if _has_member_or_namespace_prefix(normalized_code, start):
            return token
        if _is_named_value_key_context(normalized_code, start, end):
            return token
        if language in {"javascript", "typescript"} and _is_object_key_or_shorthand_context(
            normalized_code, start, end
        ):
            return token
        if token == symbol_name and symbol_name:
            return symbol_alias
        if token in preserve_exact or lowered in preserve_lowered or token.startswith("__") and token.endswith("__"):
            return token
        if _looks_like_external_pascal_symbol(token, local_symbols=local_symbols):
            return token

        replacement = replacements.get(token)
        if replacement is not None:
            return replacement

        if token in local_class_symbols:
            replacement = f"CLASS_{next_class_index}"
            next_class_index += 1
        elif token in local_function_symbols:
            replacement = f"FUNC_{next_function_index}"
            next_function_index += 1
        elif token in local_variable_symbols:
            replacement = f"VAR_{next_var_index}"
            next_var_index += 1
        else:
            return token

        replacements[token] = replacement
        return replacement

    parts: list[str] = []
    cursor = 0
    for start, end in _iter_string_ranges(normalized_code, language=language):
        if start > cursor:
            parts.append(
                _replace_identifiers_in_segment(
                    normalized_code[cursor:start],
                    absolute_start=cursor,
                    replace_token=replace_token,
                )
            )
        parts.append(
            _normalize_string_literal_segment(
                language=language,
                segment=normalized_code[start:end],
                absolute_start=start,
                replace_token=replace_token,
                string_replacements=string_replacements,
                next_string_index=next_string_index,
            )
        )
        cursor = end
    if cursor < len(normalized_code):
        parts.append(
            _replace_identifiers_in_segment(
                normalized_code[cursor:],
                absolute_start=cursor,
                replace_token=replace_token,
            )
        )
    return "".join(parts)


def collect_symbol_spans(content_bytes: bytes, language: str, tree: Tree) -> list[SymbolSpan]:
    root = tree.root_node
    stack: list[Node] = [root]
    spans: list[SymbolSpan] = []
    seen_ranges: set[tuple[str, int, int, str]] = set()

    while stack:
        node = stack.pop()
        stack.extend(reversed(list(node.children)))

        chunk_type = _node_matches_chunk_type(language, node)
        if chunk_type is None or _should_skip_decorated_python_node(language, node):
            continue

        line_start = int(node.start_point[0]) + 1
        line_end = int(node.end_point[0]) + 1
        if line_start <= 0 or line_end < line_start:
            continue

        symbol_target = node
        if language == "python" and str(node.type or "") == "decorated_definition":
            decorated_target = _get_decorated_python_target(node)
            if decorated_target is not None:
                symbol_target = decorated_target

        symbol_name = _extract_symbol_name(content_bytes, symbol_target)
        param_count = (
            _estimate_param_count(_decode_node_text(content_bytes, symbol_target))
            if chunk_type == "function"
            else 0
        )

        range_key = (chunk_type, line_start, line_end, symbol_name)
        if range_key in seen_ranges:
            continue
        seen_ranges.add(range_key)
        spans.append(
            SymbolSpan(
                chunk_type=chunk_type,
                symbol_type=chunk_type,
                symbol_name=symbol_name,
                param_count=param_count,
                line_start=line_start,
                line_end=line_end,
                start_byte=int(node.start_byte),
                end_byte=int(node.end_byte),
                node_type=str(node.type or ""),
            )
        )

    spans.sort(key=lambda span: (span.line_start, span.line_end, span.chunk_type, span.symbol_name))
    return spans


def _is_inline_callback_arrow_function(node: Node) -> bool:
    current = getattr(node, "parent", None)
    depth = 0
    while current is not None and depth < 5:
        current_type = str(current.type or "")
        if current_type in INLINE_CALLBACK_ANCESTOR_TYPES:
            return True
        if current_type in NAMED_ARROW_PARENT_TYPES:
            return False
        current = getattr(current, "parent", None)
        depth += 1
    return False


def _is_trivial_candidate(
    *,
    span: SymbolSpan,
    node: Node,
    language: str,
    normalized_code: str,
    identifier_tokens: list[str],
    call_tokens: list[str],
    ast_node_sequence: list[str],
    structure_signature: str,
    nested_function_symbols: set[str],
) -> bool:
    node_type = str(span.node_type or "")
    node_type_tokens = _node_type_tokens(node_type)
    ast_types = set(ast_node_sequence)

    if language in {"c", "cpp"} and node_type == "function_declarator":
        return True
    if language == "go" and node_type == "struct_type":
        return True
    if language in {"php", "javascript", "typescript"} and node_type in {
        "function_call_expression",
        "member_call_expression",
    }:
        return True

    if span.chunk_type == "function":
        if node_type in PARAMETER_CONTAINER_TYPES or "parameter" in node_type_tokens:
            return True
        if ast_types and ast_types.issubset(TRIVIAL_ONLY_AST_NODE_TYPES):
            return True
        if structure_signature == "function|params" and not call_tokens:
            return True
        if node_type == "arrow_function" and not identifier_tokens and not call_tokens:
            return True
        if (
            language in {"javascript", "typescript"}
            and node_type == "arrow_function"
            and _is_inline_callback_arrow_function(node)
        ):
            return True
        if normalized_code.strip() in {"()", "{}"}:
            return True

    if span.chunk_type == "class":
        if nested_function_symbols:
            return True
        if ast_types and ast_types.issubset(TRIVIAL_CLASS_AST_NODE_TYPES):
            return True

    return False


def build_code_chunk_candidates(
    *,
    content: str,
    content_bytes: bytes,
    tree: Tree,
    language: str,
    min_symbol_lines: int,
    max_symbol_lines: int,
    identifier_token_cap: int,
    call_token_cap: int,
    ast_node_sequence_cap: int,
) -> tuple[list[CodeChunkCandidate], int]:
    candidates: list[CodeChunkCandidate] = []
    filtered_count = 0
    root = tree.root_node
    if bool(getattr(root, "has_error", False)):
        return candidates, filtered_count

    spans = collect_symbol_spans(content_bytes, language, tree)
    if not spans:
        return candidates, filtered_count

    spans_by_range = {(span.start_byte, span.end_byte): span for span in spans}
    stack = [root]
    while stack:
        node = stack.pop()
        stack.extend(reversed(list(node.children)))
        span = spans_by_range.get((int(node.start_byte), int(node.end_byte)))
        if span is None:
            continue

        raw_bytes = content_bytes[span.start_byte : span.end_byte]
        raw_code = raw_bytes.decode("utf-8", errors="ignore").strip()
        if not raw_code:
            filtered_count += 1
            continue

        line_count = span.line_end - span.line_start + 1
        if line_count < max(1, min_symbol_lines) or line_count > max(1, max_symbol_lines):
            filtered_count += 1
            continue

        if _contains_generated_marker(raw_code):
            filtered_count += 1
            continue

        normalized_code = _normalize_code(raw_code, raw_bytes, node)
        if not normalized_code.strip():
            filtered_count += 1
            continue

        identifier_tokens = _collect_identifier_tokens(
            content_bytes,
            node,
            cap=max(1, identifier_token_cap),
        )
        if not identifier_tokens:
            regex_identifiers = IDENTIFIER_RE.findall(normalized_code)
            identifier_tokens = _ordered_unique(regex_identifiers, cap=max(1, identifier_token_cap))

        call_tokens = _collect_call_tokens(
            content_bytes,
            node,
            language=language,
            cap=max(1, call_token_cap),
        )
        operator_tokens = _collect_operator_tokens(content_bytes, node)
        ast_node_sequence = _collect_ast_node_sequence(node, cap=max(1, ast_node_sequence_cap))
        structure_signature = _build_structure_signature(span.chunk_type, ast_node_sequence)
        anonymization_context = _build_anonymization_context(content_bytes, node, language)
        if language in {"javascript", "typescript"} and span.chunk_type == "function":
            anonymization_context = AnonymizationContext(
                imported_symbols=anonymization_context.imported_symbols,
                local_variable_symbols=anonymization_context.local_variable_symbols
                | _extract_js_ts_header_parameter_names(normalized_code),
                local_function_symbols=anonymization_context.local_function_symbols,
                local_class_symbols=anonymization_context.local_class_symbols,
            )
        control_flow_tags = _collect_control_flow_tags(
            ast_node_sequence=ast_node_sequence,
            symbol_name=span.symbol_name,
            call_tokens=call_tokens,
        )
        if _is_trivial_candidate(
            span=span,
            node=node,
            language=language,
            normalized_code=normalized_code,
            identifier_tokens=identifier_tokens,
            call_tokens=call_tokens,
            ast_node_sequence=ast_node_sequence,
            structure_signature=structure_signature,
            nested_function_symbols=anonymization_context.local_function_symbols,
        ):
            filtered_count += 1
            continue
        anonymized_code = _anonymize_code(
            language=language,
            normalized_code=normalized_code,
            symbol_name=span.symbol_name,
            chunk_type=span.chunk_type,
            call_tokens=call_tokens,
            imported_symbols=anonymization_context.imported_symbols,
            local_variable_symbols=anonymization_context.local_variable_symbols,
            local_function_symbols=anonymization_context.local_function_symbols,
            local_class_symbols=anonymization_context.local_class_symbols,
        )
        anonymized_code = _canonicalize_named_arrow_function_code(
            anonymized_code,
            node_type=span.node_type,
            symbol_name=span.symbol_name,
        )

        candidates.append(
            CodeChunkCandidate(
                chunk_type=span.chunk_type,
                symbol_type=span.symbol_type,
                symbol_name=span.symbol_name,
                param_count=span.param_count,
                line_start=span.line_start,
                line_end=span.line_end,
                node_type=span.node_type,
                raw_code=raw_code,
                normalized_code=normalized_code,
                anonymized_code=anonymized_code,
                identifier_tokens=identifier_tokens,
                call_tokens=call_tokens,
                operator_tokens=operator_tokens,
                control_flow_tags=control_flow_tags,
                structure_signature=structure_signature,
                ast_node_sequence=ast_node_sequence,
                raw_hash=hashlib.sha1(raw_code.encode("utf-8")).hexdigest(),
                normalized_hash=hashlib.sha1(normalized_code.encode("utf-8")).hexdigest(),
                anonymized_hash=hashlib.sha1(anonymized_code.encode("utf-8")).hexdigest(),
                validation_status="valid",
            )
        )

    return candidates, filtered_count
