import hashlib
import keyword
import re
from dataclasses import dataclass
from typing import Any

from worker.common.config import settings

try:
    from tree_sitter import Node, Tree
except ImportError:  # pragma: no cover - optional dependency fallback
    Node = Any
    Tree = Any


CODE_CHUNK_INDEX_TEMPLATE_NAME = "code_chunk_index"
CODE_CHUNK_INDEX_ALIAS = settings.code_chunk_index_alias

FUNCTION_NODE_TYPES_BY_LANGUAGE = {
    "python": {"function_definition", "decorated_definition"},
    "javascript": {
        "function_declaration",
        "generator_function_declaration",
        "method_definition",
        "arrow_function",
    },
    "typescript": {
        "function_declaration",
        "generator_function_declaration",
        "method_definition",
        "arrow_function",
    },
    "java": {"method_declaration", "constructor_declaration"},
    "go": {"function_declaration", "method_declaration"},
    "rust": {"function_item"},
    "c": {"function_definition"},
    "cpp": {"function_definition"},
    "csharp": {"method_declaration", "constructor_declaration", "local_function_statement"},
    "php": {"function_definition", "method_declaration"},
    "ruby": {"method"},
    "swift": {
        "function_declaration",
        "initializer_declaration",
        "deinitializer_declaration",
    },
    "kotlin": {"function_declaration", "secondary_constructor"},
    "scala": {"function_definition"},
    "shell": {"function_definition"},
    "sql": {"create_function_statement", "create_procedure_statement"},
}

CLASS_NODE_TYPES_BY_LANGUAGE = {
    "python": {"class_definition"},
    "javascript": {"class_declaration", "class"},
    "typescript": {"class_declaration", "class"},
    "java": {"class_declaration", "record_declaration", "interface_declaration"},
    "go": {"type_declaration"},
    "rust": {"struct_item", "enum_item", "trait_item", "impl_item"},
    "csharp": {"class_declaration", "struct_declaration", "interface_declaration"},
    "php": {"class_declaration", "interface_declaration", "trait_declaration"},
    "ruby": {"class", "module"},
    "swift": {"class_declaration", "struct_declaration", "protocol_declaration", "actor_declaration"},
    "kotlin": {"class_declaration", "object_declaration", "interface_declaration"},
    "scala": {"class_definition", "object_definition", "trait_definition"},
}

IDENTIFIER_NODE_TYPES = {
    "identifier",
    "property_identifier",
    "field_identifier",
    "type_identifier",
    "simple_identifier",
    "name",
    "constant",
    "namespace_identifier",
}

SYMBOL_NAME_NODE_TYPES = (
    "identifier",
    "property_identifier",
    "field_identifier",
    "type_identifier",
    "simple_identifier",
    "name",
)

PARAMETER_CONTAINER_TYPES = {
    "parameters",
    "formal_parameters",
    "parameter_list",
    "parameter_clause",
    "arguments",
}

LOCAL_BINDING_FIELD_NAMES = (
    "name",
    "left",
    "pattern",
    "alias",
    "target",
)

IMPORT_NODE_TYPE_MARKERS = (
    "import",
    "using",
    "include",
    "require",
)

LOCAL_VARIABLE_NODE_TYPE_MARKERS = (
    "assignment",
    "declaration",
    "declarator",
    "parameter",
    "pattern",
    "for",
    "catch",
    "except",
    "with",
)

CONTROL_FLOW_NODE_TYPE_TAGS = (
    ("if_statement", "if"),
    ("if_expression", "if"),
    ("conditional_expression", "if"),
    ("for_statement", "loop"),
    ("for_in_statement", "loop"),
    ("while_statement", "loop"),
    ("do_statement", "loop"),
    ("loop_expression", "loop"),
    ("foreach_statement", "loop"),
    ("try_statement", "try"),
    ("catch_clause", "try"),
    ("except_clause", "try"),
    ("match_statement", "match"),
    ("switch_statement", "match"),
    ("switch_expression", "match"),
    ("async_function", "async"),
    ("await_expression", "async"),
    ("yield_expression", "yield"),
)

STRUCTURE_NODE_CATEGORIES = (
    ("class", "class"),
    ("function", "function"),
    ("method", "function"),
    ("parameter", "params"),
    ("assignment", "assign"),
    ("declaration", "declare"),
    ("binary", "binary_op"),
    ("unary", "unary_op"),
    ("call", "call"),
    ("return", "return"),
    ("if", "if"),
    ("for", "loop"),
    ("while", "loop"),
    ("loop", "loop"),
    ("try", "try"),
    ("catch", "try"),
    ("match", "match"),
    ("switch", "match"),
    ("await", "async"),
    ("async", "async"),
    ("yield", "yield"),
)

COMMENT_MARKERS = (
    "auto-generated",
    "autogenerated",
    "generated by",
    "generated file",
    "do not edit",
)

COMMON_RESERVED_WORDS = {
    *keyword.kwlist,
    "true",
    "false",
    "null",
    "nil",
    "none",
    "self",
    "cls",
    "this",
    "super",
    "new",
    "def",
    "class",
    "return",
    "func",
    "interface",
    "struct",
    "enum",
    "trait",
    "module",
    "package",
    "import",
    "from",
    "as",
    "async",
    "await",
    "yield",
    "try",
    "catch",
    "except",
    "finally",
    "if",
    "else",
    "elif",
    "for",
    "while",
    "switch",
    "case",
    "match",
    "break",
    "continue",
    "pass",
    "lambda",
    "with",
    "public",
    "private",
    "protected",
    "internal",
    "static",
    "final",
    "const",
    "var",
    "let",
    "void",
    "int",
    "float",
    "double",
    "bool",
    "boolean",
    "string",
}

IDENTIFIER_RE = re.compile(r"\b[A-Za-z_][A-Za-z0-9_]*\b")
CALL_TOKEN_RE = re.compile(r"\b([A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)*)\s*\(")

OPERATOR_TOKEN_MAP = (
    ("==", "eq"),
    ("!=", "neq"),
    ("<=", "lte"),
    (">=", "gte"),
    ("&&", "and"),
    ("||", "or"),
    ("=>", "arrow"),
    ("->", "member"),
    ("+", "add"),
    ("-", "sub"),
    ("*", "mul"),
    ("/", "div"),
    ("%", "mod"),
    ("=", "assign"),
    ("<", "lt"),
    (">", "gt"),
)

SIGNIFICANT_NODE_SKIP_TYPES = {
    "comment",
    "identifier",
    "property_identifier",
    "field_identifier",
    "type_identifier",
    "simple_identifier",
    "name",
    "block",
    "statement_block",
}


@dataclass(frozen=True, slots=True)
class SymbolSpan:
    chunk_type: str
    symbol_type: str
    symbol_name: str
    param_count: int
    line_start: int
    line_end: int
    start_byte: int
    end_byte: int
    node_type: str


@dataclass(frozen=True, slots=True)
class CodeChunkCandidate:
    chunk_type: str
    symbol_type: str
    symbol_name: str
    param_count: int
    line_start: int
    line_end: int
    node_type: str
    raw_code: str
    normalized_code: str
    anonymized_code: str
    identifier_tokens: list[str]
    call_tokens: list[str]
    operator_tokens: list[str]
    control_flow_tags: list[str]
    structure_signature: str
    ast_node_sequence: list[str]
    raw_hash: str
    normalized_hash: str
    anonymized_hash: str
    validation_status: str


@dataclass(frozen=True, slots=True)
class AnonymizationContext:
    imported_symbols: set[str]
    local_variable_symbols: set[str]
    local_function_symbols: set[str]
    local_class_symbols: set[str]


def build_code_chunk_id(
    *,
    repo_id: str,
    file_path: str,
    chunk_type: str,
    start_line: int,
    end_line: int,
    symbol_name: str,
    chunker_version: str,
) -> str:
    digest_input = "|".join(
        [
            repo_id,
            file_path,
            chunk_type,
            str(start_line),
            str(end_line),
            symbol_name,
            chunker_version,
        ]
    )
    return hashlib.sha1(digest_input.encode("utf-8")).hexdigest()


def _ordered_unique(values: list[str], *, cap: int) -> list[str]:
    normalized_cap = max(0, cap)
    ordered: list[str] = []
    seen: set[str] = set()
    for value in values:
        normalized = str(value or "").strip()
        if not normalized or normalized in seen:
            continue
        seen.add(normalized)
        ordered.append(normalized)
        if normalized_cap and len(ordered) >= normalized_cap:
            break
    return ordered


def _decode_node_text(content_bytes: bytes, node: Node) -> str:
    try:
        return content_bytes[node.start_byte : node.end_byte].decode("utf-8", errors="ignore")
    except Exception:  # noqa: BLE001 - best effort decode only
        return ""


def _contains_generated_marker(raw_code: str) -> bool:
    header = "\n".join(raw_code.splitlines()[:5]).lower()
    return any(marker in header for marker in COMMENT_MARKERS)


def _should_skip_decorated_python_node(language: str, node: Node) -> bool:
    parent = getattr(node, "parent", None)
    if language != "python" or parent is None:
        return False
    node_type = str(node.type or "")
    parent_type = str(parent.type or "")
    if node_type in {"function_definition", "class_definition"} and parent_type == "decorated_definition":
        return True
    return False


def _node_matches_chunk_type(language: str, node: Node) -> str | None:
    node_type = str(node.type or "")
    if not node_type or not node.is_named:
        return None

    function_node_types = FUNCTION_NODE_TYPES_BY_LANGUAGE.get(language, set())
    class_node_types = CLASS_NODE_TYPES_BY_LANGUAGE.get(language, set())

    if node_type in function_node_types:
        return "function"
    if node_type in class_node_types:
        return "class"

    lowered = node_type.lower()
    if "function" in lowered or "method" in lowered or "constructor" in lowered:
        return "function"
    if "class" in lowered or "interface" in lowered or "struct" in lowered or "trait" in lowered:
        return "class"
    return None


def _extract_symbol_name(content_bytes: bytes, node: Node) -> str:
    for child in node.children:
        if not child.is_named:
            continue
        child_type = str(child.type or "")
        if child_type in SYMBOL_NAME_NODE_TYPES:
            value = _decode_node_text(content_bytes, child).strip()
            if value:
                return value

    stack = [child for child in reversed(node.children) if child.is_named]
    while stack:
        child = stack.pop()
        child_type = str(child.type or "")
        if child_type in SYMBOL_NAME_NODE_TYPES:
            value = _decode_node_text(content_bytes, child).strip()
            if value:
                return value
        stack.extend(reversed([grand for grand in child.children if grand.is_named]))

    return ""


def _estimate_param_count(raw_code: str) -> int:
    header_lines = raw_code.splitlines()[:3]
    header = " ".join(line.strip() for line in header_lines)
    match = re.search(r"\((.*?)\)", header)
    if not match:
        return 0
    inside = match.group(1).strip()
    if not inside:
        return 0
    parts = [chunk.strip() for chunk in inside.split(",")]
    return len([part for part in parts if part])


def _collect_identifier_texts(content_bytes: bytes, node: Node) -> list[str]:
    tokens: list[str] = []
    stack = [node]
    while stack:
        current = stack.pop()
        if not current.is_named:
            continue
        current_type = str(current.type or "")
        if current_type in IDENTIFIER_NODE_TYPES:
            token = _decode_node_text(content_bytes, current).strip()
            if token:
                tokens.append(token)
        stack.extend(reversed(list(current.children)))
    return tokens


def _ordered_unique_set(values: list[str]) -> set[str]:
    return {value for value in _ordered_unique(values, cap=0) if value}


def _find_child_by_field_names(node: Node, field_names: tuple[str, ...]) -> Node | None:
    child_by_field_name = getattr(node, "child_by_field_name", None)
    if not callable(child_by_field_name):
        return None
    for field_name in field_names:
        child = child_by_field_name(field_name)
        if child is not None:
            return child
    return None


def _find_parameter_container(node: Node) -> Node | None:
    for child in node.children:
        if not child.is_named:
            continue
        child_type = str(child.type or "")
        if child_type in PARAMETER_CONTAINER_TYPES:
            return child
    return None


def _is_import_like_node(node_type: str) -> bool:
    lowered = node_type.lower()
    return any(marker in lowered for marker in IMPORT_NODE_TYPE_MARKERS)


def _is_local_variable_like_node(node_type: str) -> bool:
    lowered = node_type.lower()
    return any(marker in lowered for marker in LOCAL_VARIABLE_NODE_TYPE_MARKERS)


def _collect_imported_symbols(content_bytes: bytes, node: Node) -> set[str]:
    imported_symbols: set[str] = set()
    stack = [node]
    while stack:
        current = stack.pop()
        if not current.is_named:
            continue
        current_type = str(current.type or "")
        if _is_import_like_node(current_type):
            alias_child = _find_child_by_field_names(current, ("alias", "name"))
            if alias_child is not None:
                imported_symbols.update(_ordered_unique_set(_collect_identifier_texts(content_bytes, alias_child)))
            else:
                imported_symbols.update(_ordered_unique_set(_collect_identifier_texts(content_bytes, current)))
        stack.extend(reversed(list(current.children)))
    return imported_symbols


def _collect_local_binding_symbols(content_bytes: bytes, node: Node) -> set[str]:
    local_symbols: set[str] = set()
    stack = [node]
    while stack:
        current = stack.pop()
        if not current.is_named:
            continue
        current_type = str(current.type or "")
        if _is_import_like_node(current_type):
            stack.extend(reversed(list(current.children)))
            continue

        binding_child = _find_child_by_field_names(current, LOCAL_BINDING_FIELD_NAMES)
        if binding_child is not None and _is_local_variable_like_node(current_type):
            local_symbols.update(_ordered_unique_set(_collect_identifier_texts(content_bytes, binding_child)))

        parameter_child = _find_parameter_container(current)
        if parameter_child is not None:
            local_symbols.update(_ordered_unique_set(_collect_identifier_texts(content_bytes, parameter_child)))

        stack.extend(reversed(list(current.children)))
    return local_symbols


def _collect_nested_symbol_names(content_bytes: bytes, node: Node, language: str) -> tuple[set[str], set[str]]:
    function_symbols: set[str] = set()
    class_symbols: set[str] = set()
    stack = list(reversed(list(node.children)))
    while stack:
        current = stack.pop()
        if not current.is_named:
            continue
        chunk_type = _node_matches_chunk_type(language, current)
        if chunk_type is not None and not _should_skip_decorated_python_node(language, current):
            symbol_name = _extract_symbol_name(content_bytes, current).strip()
            if symbol_name:
                if chunk_type == "function":
                    function_symbols.add(symbol_name)
                elif chunk_type == "class":
                    class_symbols.add(symbol_name)
        stack.extend(reversed(list(current.children)))
    return function_symbols, class_symbols


def _build_anonymization_context(content_bytes: bytes, node: Node, language: str) -> AnonymizationContext:
    imported_symbols = _collect_imported_symbols(content_bytes, node)
    local_variable_symbols = _collect_local_binding_symbols(content_bytes, node)
    local_function_symbols, local_class_symbols = _collect_nested_symbol_names(content_bytes, node, language)
    local_variable_symbols -= imported_symbols
    local_function_symbols -= imported_symbols
    local_class_symbols -= imported_symbols
    return AnonymizationContext(
        imported_symbols=imported_symbols,
        local_variable_symbols=local_variable_symbols,
        local_function_symbols=local_function_symbols,
        local_class_symbols=local_class_symbols,
    )


def _collect_comment_ranges(node: Node) -> list[tuple[int, int]]:
    ranges: list[tuple[int, int]] = []
    stack = [node]
    while stack:
        current = stack.pop()
        node_type = str(current.type or "")
        if "comment" in node_type:
            ranges.append((current.start_byte, current.end_byte))
        stack.extend(reversed(list(current.children)))
    ranges.sort()
    return ranges


def _remove_comment_ranges(raw_bytes: bytes, comment_ranges: list[tuple[int, int]], start_byte: int) -> bytes:
    if not comment_ranges:
        return raw_bytes

    pieces: list[bytes] = []
    cursor = start_byte
    end_byte = start_byte + len(raw_bytes)
    for comment_start, comment_end in comment_ranges:
        bounded_start = max(start_byte, min(comment_start, end_byte))
        bounded_end = max(start_byte, min(comment_end, end_byte))
        if bounded_start > cursor:
            pieces.append(raw_bytes[cursor - start_byte : bounded_start - start_byte])
        cursor = max(cursor, bounded_end)
    if cursor < end_byte:
        pieces.append(raw_bytes[cursor - start_byte : end_byte - start_byte])
    return b"".join(pieces)


def _normalize_code(raw_code: str, raw_bytes: bytes, node: Node) -> str:
    comment_ranges = _collect_comment_ranges(node)
    normalized_bytes = _remove_comment_ranges(raw_bytes, comment_ranges, node.start_byte)
    normalized_text = normalized_bytes.decode("utf-8", errors="ignore")

    collapsed_lines: list[str] = []
    previous_blank = False
    for line in normalized_text.splitlines():
        compact_line = re.sub(r"[ \t]+", " ", line.rstrip())
        if not compact_line.strip():
            if previous_blank:
                continue
            collapsed_lines.append("")
            previous_blank = True
            continue
        collapsed_lines.append(compact_line)
        previous_blank = False

    return "\n".join(collapsed_lines).strip()


def _collect_identifier_tokens(content_bytes: bytes, node: Node, *, cap: int) -> list[str]:
    tokens: list[str] = []
    stack = [node]
    while stack:
        current = stack.pop()
        current_type = str(current.type or "")
        if current_type in IDENTIFIER_NODE_TYPES:
            token = _decode_node_text(content_bytes, current).strip()
            if token:
                tokens.append(token)
        stack.extend(reversed([child for child in current.children if child.is_named]))
    return _ordered_unique(tokens, cap=cap)


def _collect_call_tokens(raw_code: str, *, cap: int) -> list[str]:
    tokens = [match.group(1) for match in CALL_TOKEN_RE.finditer(raw_code)]
    return _ordered_unique(tokens, cap=cap)


def _collect_operator_tokens(raw_code: str) -> list[str]:
    ordered: list[str] = []
    seen: set[str] = set()
    lowered_code = raw_code.lower()
    for symbol, token in OPERATOR_TOKEN_MAP:
        if symbol in raw_code and token not in seen:
            ordered.append(token)
            seen.add(token)
    for keyword_token, token in ((" and ", "and"), (" or ", "or"), (" not ", "not")):
        if keyword_token in f" {lowered_code} " and token not in seen:
            ordered.append(token)
            seen.add(token)
    return ordered


def _collect_ast_node_sequence(node: Node, *, cap: int) -> list[str]:
    sequence: list[str] = []
    stack = [node]
    while stack and len(sequence) < max(1, cap):
        current = stack.pop()
        if not current.is_named:
            continue
        current_type = str(current.type or "")
        if not current_type or current_type in SIGNIFICANT_NODE_SKIP_TYPES:
            stack.extend(reversed([child for child in current.children if child.is_named]))
            continue
        sequence.append(current_type)
        stack.extend(reversed([child for child in current.children if child.is_named]))
    return sequence


def _build_structure_signature(chunk_type: str, ast_node_sequence: list[str]) -> str:
    parts = [chunk_type]
    for node_type in ast_node_sequence:
        lowered = node_type.lower()
        for marker, category in STRUCTURE_NODE_CATEGORIES:
            if marker in lowered and category not in parts:
                parts.append(category)
                break
        if len(parts) >= 6:
            break
    return "|".join(parts)


def _collect_control_flow_tags(
    *,
    ast_node_sequence: list[str],
    symbol_name: str,
    call_tokens: list[str],
) -> list[str]:
    tags: list[str] = []
    seen: set[str] = set()

    lowered_node_types = [node_type.lower() for node_type in ast_node_sequence]
    for node_type, tag in CONTROL_FLOW_NODE_TYPE_TAGS:
        if any(node_type in lowered for lowered in lowered_node_types) and tag not in seen:
            tags.append(tag)
            seen.add(tag)

    if symbol_name and any(token == symbol_name or token.endswith(f".{symbol_name}") for token in call_tokens):
        if "recursion" not in seen:
            tags.append("recursion")
            seen.add("recursion")

    if not tags:
        return ["none"]
    return tags


def _looks_like_external_pascal_symbol(token: str, *, local_symbols: set[str]) -> bool:
    if token in local_symbols:
        return False
    if not token or "_" in token:
        return False
    if not token[0].isupper():
        return False
    return any(char.islower() for char in token[1:])


def _anonymize_code(
    *,
    normalized_code: str,
    symbol_name: str,
    chunk_type: str,
    call_tokens: list[str],
    imported_symbols: set[str],
    local_variable_symbols: set[str],
    local_function_symbols: set[str],
    local_class_symbols: set[str],
) -> str:
    preserve: set[str] = set(COMMON_RESERVED_WORDS)
    preserve.update(imported_symbols)
    local_symbols = local_variable_symbols | local_function_symbols | local_class_symbols
    for token in call_tokens:
        parts = [part for part in token.split(".") if part]
        if not parts:
            continue
        if len(parts) == 1:
            continue
        if parts[0] not in local_symbols:
            preserve.add(parts[0])
        preserve.update(parts[1:])

    replacements: dict[str, str] = {}
    next_var_index = 0
    next_function_index = 1
    next_class_index = 1
    symbol_alias = "CLASS_0" if chunk_type == "class" else "FUNC_0"

    def replace(match: re.Match[str]) -> str:
        nonlocal next_var_index, next_function_index, next_class_index
        token = match.group(0)
        lowered = token.lower()
        if token == symbol_name and symbol_name:
            return symbol_alias
        if lowered in preserve or token.startswith("__") and token.endswith("__"):
            return token
        if _looks_like_external_pascal_symbol(token, local_symbols=local_symbols):
            return token

        replacement = replacements.get(token)
        if replacement is not None:
            return replacement

        if token in local_class_symbols:
            replacement = f"CLASS_{next_class_index}"
            next_class_index += 1
        elif token in local_function_symbols:
            replacement = f"FUNC_{next_function_index}"
            next_function_index += 1
        elif token in local_variable_symbols or token not in preserve:
            replacement = f"VAR_{next_var_index}"
            next_var_index += 1
        else:
            return token

        replacements[token] = replacement
        return replacement

    return IDENTIFIER_RE.sub(replace, normalized_code)


def collect_symbol_spans(content_bytes: bytes, language: str, tree: Tree) -> list[SymbolSpan]:
    root = tree.root_node
    stack: list[Node] = [root]
    spans: list[SymbolSpan] = []
    seen_ranges: set[tuple[str, int, int, str]] = set()

    while stack:
        node = stack.pop()
        stack.extend(reversed(list(node.children)))

        chunk_type = _node_matches_chunk_type(language, node)
        if chunk_type is None or _should_skip_decorated_python_node(language, node):
            continue

        line_start = int(node.start_point[0]) + 1
        line_end = int(node.end_point[0]) + 1
        if line_start <= 0 or line_end < line_start:
            continue

        symbol_name = _extract_symbol_name(content_bytes, node)
        param_count = _estimate_param_count(_decode_node_text(content_bytes, node)) if chunk_type == "function" else 0

        range_key = (chunk_type, line_start, line_end, symbol_name)
        if range_key in seen_ranges:
            continue
        seen_ranges.add(range_key)
        spans.append(
            SymbolSpan(
                chunk_type=chunk_type,
                symbol_type=chunk_type,
                symbol_name=symbol_name,
                param_count=param_count,
                line_start=line_start,
                line_end=line_end,
                start_byte=int(node.start_byte),
                end_byte=int(node.end_byte),
                node_type=str(node.type or ""),
            )
        )

    spans.sort(key=lambda span: (span.line_start, span.line_end, span.chunk_type, span.symbol_name))
    return spans


def build_code_chunk_candidates(
    *,
    content: str,
    content_bytes: bytes,
    tree: Tree,
    language: str,
    min_symbol_lines: int,
    max_symbol_lines: int,
    identifier_token_cap: int,
    call_token_cap: int,
    ast_node_sequence_cap: int,
) -> tuple[list[CodeChunkCandidate], int]:
    candidates: list[CodeChunkCandidate] = []
    filtered_count = 0
    root = tree.root_node
    if bool(getattr(root, "has_error", False)):
        return candidates, filtered_count

    spans = collect_symbol_spans(content_bytes, language, tree)
    if not spans:
        return candidates, filtered_count

    spans_by_range = {(span.start_byte, span.end_byte): span for span in spans}
    stack = [root]
    while stack:
        node = stack.pop()
        stack.extend(reversed(list(node.children)))
        span = spans_by_range.get((int(node.start_byte), int(node.end_byte)))
        if span is None:
            continue

        raw_bytes = content_bytes[span.start_byte : span.end_byte]
        raw_code = raw_bytes.decode("utf-8", errors="ignore").strip()
        if not raw_code:
            filtered_count += 1
            continue

        line_count = span.line_end - span.line_start + 1
        if line_count < max(1, min_symbol_lines) or line_count > max(1, max_symbol_lines):
            filtered_count += 1
            continue

        if _contains_generated_marker(raw_code):
            filtered_count += 1
            continue

        normalized_code = _normalize_code(raw_code, raw_bytes, node)
        if not normalized_code.strip():
            filtered_count += 1
            continue

        identifier_tokens = _collect_identifier_tokens(
            content_bytes,
            node,
            cap=max(1, identifier_token_cap),
        )
        if not identifier_tokens:
            regex_identifiers = IDENTIFIER_RE.findall(normalized_code)
            identifier_tokens = _ordered_unique(regex_identifiers, cap=max(1, identifier_token_cap))

        call_tokens = _collect_call_tokens(raw_code, cap=max(1, call_token_cap))
        operator_tokens = _collect_operator_tokens(raw_code)
        ast_node_sequence = _collect_ast_node_sequence(node, cap=max(1, ast_node_sequence_cap))
        structure_signature = _build_structure_signature(span.chunk_type, ast_node_sequence)
        anonymization_context = _build_anonymization_context(content_bytes, node, language)
        control_flow_tags = _collect_control_flow_tags(
            ast_node_sequence=ast_node_sequence,
            symbol_name=span.symbol_name,
            call_tokens=call_tokens,
        )
        anonymized_code = _anonymize_code(
            normalized_code=normalized_code,
            symbol_name=span.symbol_name,
            chunk_type=span.chunk_type,
            call_tokens=call_tokens,
            imported_symbols=anonymization_context.imported_symbols,
            local_variable_symbols=anonymization_context.local_variable_symbols,
            local_function_symbols=anonymization_context.local_function_symbols,
            local_class_symbols=anonymization_context.local_class_symbols,
        )

        candidates.append(
            CodeChunkCandidate(
                chunk_type=span.chunk_type,
                symbol_type=span.symbol_type,
                symbol_name=span.symbol_name,
                param_count=span.param_count,
                line_start=span.line_start,
                line_end=span.line_end,
                node_type=span.node_type,
                raw_code=raw_code,
                normalized_code=normalized_code,
                anonymized_code=anonymized_code,
                identifier_tokens=identifier_tokens,
                call_tokens=call_tokens,
                operator_tokens=operator_tokens,
                control_flow_tags=control_flow_tags,
                structure_signature=structure_signature,
                ast_node_sequence=ast_node_sequence,
                raw_hash=hashlib.sha1(raw_code.encode("utf-8")).hexdigest(),
                normalized_hash=hashlib.sha1(normalized_code.encode("utf-8")).hexdigest(),
                anonymized_hash=hashlib.sha1(anonymized_code.encode("utf-8")).hexdigest(),
                validation_status="valid",
            )
        )

    return candidates, filtered_count
